version: '3.8'

name: cfp-energy-test

services:
  laravel:
    container_name: cfp-energy-laravel
    build:
      context: .
      dockerfile: ./docker/laravel/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: cfp-energy-db
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  proxy:
    container_name: cfp-energy-proxy
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./public:/app/public
    depends_on:
      - laravel

  vite:
    container_name: cfp-energy-vite
    image: node:18-alpine
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: /bin/sh -c "npm --ignore-scripts install && npm --ignore-scripts run dev"

volumes:
  postgres_data: # volume for persisting postgres data
